import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import imageStyles from '@/styles/Images.module.css'
import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main + ' ' + roboto.className}>
        <div className={styles.IntroContainer}>
          <div className={styles.MeImageContainer}>
            <Image
            className={imageStyles.MeImage}
            alt='me.jpg'
            src={'/ME.jpg'}
            height={300}
            width={300}
            />
          </div>
          <div className={styles.MeDescriptionContainer}>
            <h1>Hello</h1>
            <h2>I'm <span>Drake Buentello</span></h2>
          </div>
        </div>

        <div>
        </div>
      </main>
    </>
  )
}
