import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '@/styles/Home.module.css'
import imageStyles from '@/styles/Images.module.css'
import { Roboto } from 'next/font/google'

import Socialbar from '@/components/socialbar/socialbar'
import Skills from '@/components/skills/skills'
import Projects from '@/components/projects/projects'
import Navbar from '@/components/navbar/navbar'

const roboto = Roboto({
  weight: ['400', '500', '700', '900'],
  subsets: ['latin'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Drake Buentello | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main + ' ' + roboto.className}>
        <div className={styles.IntroContainer}>
          <div className={styles.MeImageContainer}>
            <Image
            className={imageStyles.MeImage}
            alt='me.jpg'
            src={'/ME.jpg'}
            height={280}
            width={280}
            />
          </div>
          <div className={styles.MeDescriptionContainer}>
            <h1>Hello Im </h1>
            <h2><span>Drake Buentello</span></h2>
          </div>
        </div>


        <div className={styles.ContentParent}>
          
          <div className={styles.AboutContainer}>
            <h2>I&apos;m a enthusiast of new techonolgies and a strong adapter of them. I believe to be successful in programming is to look deeper beyond abstraction, to understand what really makes it work. I am currently a student enrolled at Wilmington Univeristy, working towards a BA of Computer Science. I have significant knowledge of both backend and frontend technologies and industry standard frameworks.</h2>
            <Link href="/About">Read More</Link>
          </div>

          <Socialbar />

          <div className={styles.SkillContainer}>
            <h1 className={styles.SectionHeader + " " + styles.WhiteHead}>Skills</h1>
            <div className={styles.SkillChild}>
              <Skills />
            </div>
          </div>

          <div className={styles.ProjectContainer}>
            <h1 className={styles.SectionHeader + " " + styles.DarkHead}>Projects</h1>
            <Projects showMore={false}/>
          </div>

        </div>
      </main>
    </>
  )
}
