import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Projects.module.css'
import imageStyles from '@/styles/Images.module.css'
import { Roboto } from 'next/font/google'

import Navbar from '@/components/navbar/navbar'
import ProjectsB from '@/components/projects/projects'
import Socialbar from '@/components/socialbar/socialbar'

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
})

export default function Projects() {
  return (
    <>
      <Head>
        <title>Drake Buentello | Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main + ' ' + roboto.className}>
        <ProjectsB showMore={true}/>
        <Socialbar />

      </main>
    </>
  )
}
